Cypress Web App/CypressWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_views # App/Folder users
from report import views as report_views # App/Folder report

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
    path('register/', user_views.register, name = 'register'),
    path('captcha/', include('captcha.urls')), 
    path('profile/', user_views.profile, name = 'profile'),
    path('profile-delete/<int:pk>/', user_views.ProfileDeleteView.as_view(), name = 'profile-delete'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('lockout/', user_views.lockout, name = 'lockout'),
    path('report/', report_views.report, name = 'report'),
    path('report-update/', report_views.report_update, name = 'report-update'),
    path('report-edit/<int:pk>/', report_views.ReportEditView.as_view(), name = 'report-edit'),
    path('report-delete/<int:pk>/', report_views.ReportDeleteView.as_view(), name = 'report-delete'),
    path('report-suggest/', report_views.ReportSuggestView.as_view(), name = 'report-suggest'),
    path('report-like/', report_views.report_like, name = 'report-like'),
    path('report-complete/', report_views.report_complete, name = 'report-complete'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cypress Web App/system/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='system-main'),
    path('portal/', views.portal, name='system-portal'),
    path('contact/', views.contact, name='system-contact'),
    path('faq/', views.faq, name='system-faq')
]

Cypress Web App/report/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

class Report(models.Model):
    problem_options = [
        ('utility_failure', 'Utility Failure'),
        ('tree_collapse', 'Tree Collapse'),
        ('potholes', 'Potholes'),
        ('flooded_streets', 'Flooded Streets'),
        ('vandalism', 'City Property Vandalism'),
        ('mould_spore', 'Mould and Spore Growth'),
        ('eroded_street', 'Eroded Street'),
        ('blocking_objects', 'Garbage or any Other Road Blocking Objects')
    ]
    notification_choices = (
        (True, 'Yes'),
        (False, 'No')
    )

    address = models.CharField(max_length=100)
    problem = models.CharField(max_length=100, choices=problem_options)
    reporter = models.ForeignKey(User, on_delete=models.CASCADE) # One-to-many relationship from User to Report
    Creation_Date_and_Time = models.DateTimeField(default=timezone.now)
    notifications = models.BooleanField(choices = notification_choices, default=False, verbose_name='Subscribe to Completion Notification')
    completed = models.BooleanField(default=False)
    likes = models.ManyToManyField(User, related_name='liked_reports')

    def __str__(self):
        return f'Report by {self.reporter.username}'

    def get_absolute_url(self):
        return reverse('report-update')

    @property
    def count_likes(self):
        return self.likes.count()

Cypress Web App/report/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
    
    class Meta:
        model = Report
        exclude = ['reporter', 'completed', 'likes']

    def __init__(self, *args, **kwargs):
        super(ReportForm, self).__init__(*args, **kwargs)
        input_attrs = {
            'id': 'problem-address',
            'name': 'problem-address',
            'autocomplete': 'on'
        }
        self.fields['address'].widget = forms.TextInput(attrs=input_attrs)

Cypress Web App/report/views.py
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, UpdateView, DeleteView
from .forms import ReportForm
from .models import Report

@login_required
def report(request):
    if request.method == 'POST':
        form = ReportForm(request.POST)
        form.fields['Creation_Date_and_Time'].disabled = True
        if form.is_valid():
            report = form.save(commit=False)
            report.reporter = request.user
            report.save()
            messages.success(request, f'Your report has been created!')
            return redirect('system-portal')
    else:
        form = ReportForm()
        form.fields['Creation_Date_and_Time'].disabled = True
    return render(request, 'report/report_problem.html', {'form': form, 'title': 'Create Report'})

@login_required
def report_update(request):
    user_reports = request.user.report_set.all().order_by('completed')
    return render(request, 'report/report_update.html', {'reports': user_reports, 'title': 'Update Report'})

@login_required
def report_like(request):
    report = get_object_or_404(Report, id=request.POST.get('report_id'))
    report.likes.add(request.user)
    return redirect('report-suggest')

@login_required
def report_complete(request):
    report = get_object_or_404(Report, id=request.POST.get('report_id'))
    report.completed = True
    report.save()
    if report.notifications:
        message = 'This e-mail is to inform you that your report created on {}, which was submitted to City of Toronto\'s Cypress system has been successfully completed and the issue has been resolved.\nThank you for helping keep the city streets clean and safe.\n\nWith Regards,\nCity Of Toronto Cypress Team'.format(report.Creation_Date_and_Time)
        send_mail(
            'Cypress Report#{0} by User: {1}'.format(report.id, report.reporter.username),
            message,
            'cypress.cps406@gmail.com',
            [report.reporter.email],
            fail_silently=False,
        )
    return redirect('report-suggest')

class ReportSuggestView(LoginRequiredMixin, ListView):
    template_name = 'report/report_suggest.html'
    queryset = Report.objects.all().order_by('completed')
    context_object_name = 'reports'

class ReportEditView(LoginRequiredMixin, UpdateView):
    model = Report
    template_name = 'report/report_problem.html'
    fields = ['address', 'problem', 'notifications']

    def form_valid(self, form):
        form.instance.reporter = self.request.user
        return super().form_valid(form)

class ReportDeleteView(LoginRequiredMixin, DeleteView):
    model = Report
    success_url = '/report-update/'

Cypress Web App/report/templates/report/report_confirm_delete.html
{% extends "system/base.html" %}
{% block content %}
    <div class="report-delete-content">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="mb-3">Delete Report</legend>
                <p>Are you sure you want to delete "Report {{ object.id }}"?</p>
            </fieldset>
            <div class="btn-options form-group">
                <button class="btn btn-outline-danger" type="submit">Delete</button>
                <a class="btn btn-outline-primary" href="{% url 'report-update' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

Cypress Web App/report/templates/report/report_list.html
{% extends "system/base.html" %}
{% block content %}
    <div class="reports-wrapper mx-auto" style="width: 100%;height: 100%;">
        {% for report in reports %}
        <div class="report" style="width: 65%;height: 65%;padding: 0.5rem 2rem;line-height: 20px;">
            <div style="padding-bottom: 10px;">
              <h3 class="report-name">Report#{{ report.id }} by User: {{ report.reporter.username }}</h3>
              <span><u>Address</u>: </span><span class="report-address">{{ report.address }}</span>
            </div>
            <div id="map" class="map-class"></div>
            <div style="line-height: 2vh;padding-top: 5px;">
              <p class="report-problem"><u>Problem</u>: {{ report.get_problem_display }}</p>
              <p class="report-date"><u>Date</u>: {{ report.Creation_Date_and_Time|date:"F d, Y | H:i:s TZ" }}</p>
              <p class="report-likes"><u>Likes</u>: {{ report.count_likes }}</p>
              <p class="report-likes"><u>Completed</u>: {{ report.completed }}</p>
            </div>
            <!-- Put buttons for likes/edit/delete inside block 'report_options' -->
              {% block report_options %}{% endblock report_options %}
        </div>
        <br><br><br><hr>
        {% endfor %}
    </div>
{% endblock content %}

{% block scripts %}
    <script 
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzXbJaMAzeK_a451DA-xZ-2O7zFbJhAVU&callback=initMap&libraries=&v=weekly" 
        async
    ></script>

    <script>
        // Initialize map
        function initMap() {
          map_elements_array = [] // Array storing all map elements in report list
          map_elements = document.getElementsByClassName("map-class"); // Gets all elements with class 'map-class'
          
          for(var i=0; i<map_elements.length; i++) { // Loops through each element, creates a map for it and pushes it into array
                const map = new google.maps.Map(map_elements[i], {
                    zoom: 8,
                    center: { lat: 43.6596817, lng: -79.3838966 },
                });
                map_elements_array.push(map);
          }

          const geocoder = new google.maps.Geocoder(); // Create new Geocoder object
          var elements = document.getElementsByClassName("report-address"); // Get all elements with class 'report-address'
          
          for(var i=0; i<elements.length; i++) { // Loop through all elements, send to geocodeLatLng function the geocoder object, map, and element associated with that map
            geocodeLatLng(geocoder, map_elements_array[i], elements[i]);
          }
        }
  
        function geocodeLatLng(geocoder, map, element) {
          const input = element.innerHTML // Get latitude longitude value
          const latlngStr = input.split(",", 2); // Split string into 2, convert to float
          const latlng = {
            lat: parseFloat(latlngStr[0]),
            lng: parseFloat(latlngStr[1]),
          };
         
          geocoder.geocode({ location: latlng }, (results, status) => { // Gets address and replaces latitude longitude value with it, also sets and focuses on marker, alerts if error present
            if (status === "OK") {
              if (results[0]) {
                map.setZoom(12);
                const marker = new google.maps.Marker({
                  position: latlng,
                  map: map,
                });
                map.panTo(marker.getPosition());
                element.innerHTML = results[0].formatted_address;
              } else {
                window.alert("No results found");
              }
            } else {
              window.alert("Geocoder failed due to: " + status);
            }
          });
        }
    </script>
{% endblock scripts %}

Cypress Web App/report/templates/report/report_problem.html
{% extends "system/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div style="padding: 1rem 2rem;">
        <h2>Report A Problem!</h2>
        <small>Click on the map below to mark a location and choose a problem from the dropdown list</small>
    </div>
    <div style="display: flex;height: 100%;padding: 0.1rem 2rem;">
        <div id="map"></div>
        <div class="register-content">
            <span>Address Chosen: </span><br><span id="address-full"></span>
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form|crispy }}
                </fieldset>
                <div class="btn-options form-group">
                    <button class="btn btn-outline-primary" type="submit">Report</button>
                    <a class="btn btn-outline-primary" href="{% url 'system-portal' %}">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script 
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCzXbJaMAzeK_a451DA-xZ-2O7zFbJhAVU&callback=initMap&libraries=&v=weekly" 
        async
    ></script>

    <script>
        var markers = []; // Initialize empty array
        // Initialize Map
        function initMap() { 
            const myLatlng = { lat: 43.6596817, lng: -79.3838966 };  // Define center latitude and longitude
            const geocoder = new google.maps.Geocoder(); // Initialize Geocoder object
            const TORONTO_BOUNDS = { // Define Toronto latitude and longitude restrictions
                north: 43.8212948,
                south: 43.5939679,
                west:  -79.6437337,
                east:  -79.0163347,
            };

            const map = new google.maps.Map(document.getElementById("map"), { // Create map with restrictions
                zoom: 4,
                center: myLatlng,
                restriction: {
                        latLngBounds: TORONTO_BOUNDS,
                        strictBounds: true,
                },
                clickableIcons: false
            });

            let infoWindow = new google.maps.InfoWindow({ // Create the initial InfoWindow
                content: "Click the map to mark a location!",
                position: myLatlng,
            });
            infoWindow.open(map);
            
            // Get elements if present (used in check if report edit or update)
            var first = document.getElementById("problem-address")
            var second = document.getElementById("id_address")

            // Check if report being edited, get selected address, convert into fully formated address, and display
            if(second && second.value) {
                const input = document.getElementById("id_address").value; // Get latitude longitude value
                const latlngStr = input.split(",", 2); // Split string into 2, convert to float
                const latlng = {
                    lat: parseFloat(latlngStr[0]),
                    lng: parseFloat(latlngStr[1]),
                };
                geocoder.geocode({ location: latlng }, (results, status) => { // Gets address and displays
                    if (status === "OK") {
                        if (results[0]) {
                            (document.getElementById("address-full")).innerHTML = results[0].formatted_address;
                        }
                    }
                });
            }
            
            map.addListener("click", (mapsMouseEvent) => { // Configure the click listener
                infoWindow.close(); // Close the current InfoWindow
                if (markers[0]) { // Remove markers if present
                    for (var i = 0; i < markers.length; i++) {
                        markers[i].setMap(null);
                    }
                    markers = [];
                }
                var marker = new google.maps.Marker({ // Create a new marker
                    position: mapsMouseEvent.latLng,
                });
                
                const input = String(mapsMouseEvent.latLng).slice(1,-1); // Get latitude longitude value
                const latlngStr = input.split(",", 2); // Split string into 2, convert to float
                const latlng = {
                    lat: parseFloat(latlngStr[0]),
                    lng: parseFloat(latlngStr[1]),
                };
                geocoder.geocode({ location: latlng }, (results, status) => { // Gets address and replaces latitude longitude value with it, also sets and focuses on marker, alerts if error present
                    if (status === "OK") {
                        if (results[0]) {
                            if (!results[0].types.includes("administrative_area_level_2") && !results[0].types.includes("political")) { // Check if clicking on water
                                (document.getElementById("address-full")).innerHTML = results[0].formatted_address;

                                // Check if report being created or edited
                                if (first) {
                                    first.value = String(mapsMouseEvent.latLng).slice(1,-1);  // Get latitude and longitude and place in address field
                                } else if (second) {
                                    second.value = String(mapsMouseEvent.latLng).slice(1,-1); // Get latitude and longitude and place in address field
                                }
                                // Add marker to array and map
                                markers.push(marker);
                                marker.setMap(map);
                            }
                            else {
                                alert("There are no roads, trees, or property on water 😠");
                            }
                        }
                    }
                });
            });
        }
    </script>
{% endblock scripts %}

Cypress Web App/report/templates/report/report_suggest.html
{% extends "report/report_list.html" %}
{% block report_options %}
    <div style="display: flex;">
    {% if not report.completed %}
        <form action="{% url 'report-like' %}" method="POST">
            {% csrf_token %}
            <button type="submit"
                name="report_id"
                value="{{ report.id }}"
                class="btn btn-outline-primary">Like</button>
        </form>
        {% if user.is_staff and not report.completed %}
            <form action="{% url 'report-complete' %}" method="POST">
                {% csrf_token %}
                <button type="submit"
                    name="report_id"
                    value="{{ report.id }}"
                    class="btn btn-outline-primary">Mark Complete</button>
            </form>
        {% endif %}
    {% else %}
        <p>The report has been completed and cannot be liked.</p>
    {% endif %}
    </div>
{% endblock report_options %}

Cypress Web App/report/templates/report/report_update.html
{% extends "report/report_list.html" %}
{% block report_options %}
    {% if not report.completed %}
        <div class="report-update-buttons">
            <a href="{% url 'report-edit' report.id %}" class="btn btn-outline-primary">Edit</a>
            <a href="{% url 'report-delete' report.id %}" class="btn btn-outline-danger">Delete</a>
        </div>
    {% else %}
        <p>The report has been completed and cannot be edited or deleted.</p>
    {% endif %}
{% endblock report_options %}